name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '0 0 */28 */1 *'

permissions: {}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: Build application
      run: go build -v ./...

    - name: Test application
      run: go test -v ./...

    - name: Coverage Reporting
      if: ${{ github.event_name == 'push' }}
      uses: shogo82148/actions-goveralls@8781f5dd05b691c4dd042d5e859c11c73e0104fa # v1.11.1
